### ISSUE TITLE
fix footer if user not logged in

### ISSUE THREAD

**Issue by tusharnankani** [varunmamtora06/FluffZone#4]
![image](https://user-images.githubusercontent.com/61280281/117489030-b7dd1880-af8a-11eb-8bf3-5cdaca2cc27d.png)

Also, link [FluffZone], in the footer, to GitHub Repository.

**Comment by varunmamtora06** [comment]
Thanks for raising an issue @tusharnankani, the footer was already fixed in issue #2 pr: #3 .
Apart from that I' ve linked the repo link to the 'FluffZone' text in footer 👍.

**Comment by tusharnankani** [comment]
Alright, the changes were not reflected earlier, but it is alright now 👍🏻
